# Generated by Django 4.2.5 on 2023-11-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('new_password', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Custom', 'Custom')], max_length=7)),
            ],
        ),
    ]
