# Generated by Django 4.2.5 on 2023-11-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='login'),
        ),
    ]
