# Generated by Django 4.2.5 on 2023-11-13 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='login',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
